# Generated by Django 5.1.6 on 2025-02-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='Topic',
            new_name='topic',
        ),
    ]
